### PR TITLE
Map/Set - New Pull Request

### PR DESCRIPTION
**Pull request by SaulDoesCode**
👨‍💻 here it is.

### CODE REVIEW

**Comment by SaulDoesCode** [comment]
🙌 Hooray!! 🙌

**Comment by benjvmin** [comment]
Merged it into the feature branch! I'll be working on adding /  tweaking a couple things I wanted to before this commit (unit testing, some other debug stuff)- if you want to continue working on it feel free to and as long as we don't have any conflicts we can continue to add it to this branch! Thank you @SaulDoesCode I'll be in touch!

**Comment by SaulDoesCode** [comment]
Sounds good, I'll see what I can do. What unit testing library are you going to use? I'd recommend [Ava.js](https://github.com/avajs/ava) just because of how simple and fully featured it is.

**Comment by benjvmin** [comment]
I believe I was gonna try out Mocha but I'll definitely take a look at Ava.js as well!

**Comment by SaulDoesCode** [comment]
How could we message each other in future?

**Pull request merged**
